# Generated by Django 5.2.7 on 2025-11-17 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreastCancerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО пациента')),
                ('stage', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Стадия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10, verbose_name='Пол')),
                ('menopausal_status', models.CharField(choices=[('premenopausal', 'Пременопауза'), ('perimenopausal', 'Перименопауза'), ('postmenopausal', 'Постменопауза'), ('not_applicable', 'Не применимо')], default='not_applicable', max_length=20, verbose_name='Менопаузальный статус')),
                ('family_history', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=10, verbose_name='Семейный анамнез')),
                ('brca_mutation', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=10, verbose_name='Мутация BRCA')),
                ('molecular_subtype', models.CharField(choices=[('HR+HER2-', 'HR+HER2-'), ('HR+HER2+', 'HR+HER2+'), ('HR-HER2+', 'HR-HER2+'), ('TNBC', 'TNBC (Трижды негативный)')], max_length=20, verbose_name='Молекулярный подтип')),
                ('er_status', models.CharField(choices=[('positive', 'Положительный'), ('negative', 'Отрицательный')], max_length=10, verbose_name='ER статус')),
                ('pr_status', models.CharField(choices=[('positive', 'Положительный'), ('negative', 'Отрицательный')], max_length=10, verbose_name='PR статус')),
                ('her2_status', models.CharField(choices=[('positive', 'Положительный'), ('negative', 'Отрицательный')], max_length=10, verbose_name='HER2 статус')),
                ('ki67_level', models.FloatField(verbose_name='Уровень Ki-67 (%)')),
                ('tumor_grade', models.CharField(choices=[('G1', 'G1'), ('G2', 'G2'), ('G3', 'G3')], max_length=2, verbose_name='Гистологическая градация')),
                ('tumor_size_before', models.FloatField(verbose_name='Размер опухоли до лечения (см)')),
                ('tumor_size_3m', models.FloatField(blank=True, null=True, verbose_name='Размер через 3 месяца (см)')),
                ('tumor_size_6m', models.FloatField(blank=True, null=True, verbose_name='Размер через 6 месяцев (см)')),
                ('tumor_size_12m', models.FloatField(blank=True, null=True, verbose_name='Размер через 12 месяцев (см)')),
                ('tumor_size_24m', models.FloatField(blank=True, null=True, verbose_name='Размер через 24 месяца (см)')),
                ('treatment', models.CharField(choices=[('surgery', 'Хирургическое лечение'), ('surgery_chemotherapy', 'Хирургия и Химиотерапия'), ('surgery_targeted', 'Хирургия и Таргетная терапия'), ('none', 'Лечение не проводилось')], max_length=50, verbose_name='Тип лечения')),
                ('surgery_type', models.CharField(choices=[('lumpectomy', 'Лампэктомия'), ('mastectomy', 'Мастэктомия'), ('none', 'Не проводилось')], max_length=20, verbose_name='Тип операции')),
                ('has_metastasis', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=10, verbose_name='Наличие метастазов')),
                ('metastasis_size', models.FloatField(blank=True, null=True, verbose_name='Размер метастаза (см)')),
                ('metastasis_sites', models.CharField(blank=True, max_length=100, verbose_name='Локализация метастазов')),
                ('lymph_node_status', models.CharField(choices=[('positive', 'Положительный'), ('negative', 'Отрицательный')], max_length=10, verbose_name='Статус лимфоузлов')),
                ('positive_lymph_nodes', models.IntegerField(verbose_name='Количество пораженных лимфоузлов')),
                ('performance_status', models.IntegerField(choices=[(0, '0 - Полностью активен'), (1, '1 - Ограниченно активен'), (2, '2 - Амбулаторный'), (3, '3 - Ограниченно самостояственный'), (4, '4 - Полностью нетрудоспособен')], verbose_name='Статус по шкале ECOG')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Данные пациента с РМЖ',
                'verbose_name_plural': 'Данные пациентов с РМЖ',
                'db_table': 'breast_cancer_data',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_hash', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('menopausal_status', models.CharField(blank=True, max_length=20, null=True)),
                ('family_history', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
        migrations.CreateModel(
            name='PathologicalProfiles',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('molecular_subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('er_status', models.CharField(blank=True, max_length=10, null=True)),
                ('pr_status', models.CharField(blank=True, max_length=10, null=True)),
                ('her2_status', models.CharField(blank=True, max_length=10, null=True)),
                ('brca_mutation', models.CharField(blank=True, max_length=10, null=True)),
                ('ki67_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tumor_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('lymph_node_status', models.CharField(blank=True, max_length=10, null=True)),
                ('positive_lymph_nodes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tumor_model.patients')),
            ],
            options={
                'db_table': 'pathological_profiles',
            },
        ),
    ]
