# Generated by Django 5.2.7 on 2025-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_hash', models.CharField(blank=True, max_length=32, unique=True)),
                ('stage', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Женский'), ('Male', 'Мужской'), ('Other', 'Другой')], max_length=10)),
                ('menopausal_status', models.CharField(blank=True, choices=[('Premenopausal', 'Пременопаузальный'), ('Perimenopausal', 'Перименопаузальный'), ('Postmenopausal', 'Постменопаузальный'), ('Unknown', 'Неизвестно')], max_length=20, null=True)),
                ('family_history', models.BooleanField(blank=True, null=True)),
                ('molecular_subtype', models.CharField(blank=True, max_length=50, null=True)),
                ('er_status', models.CharField(blank=True, max_length=10, null=True)),
                ('pr_status', models.CharField(blank=True, max_length=10, null=True)),
                ('her2_status', models.CharField(blank=True, max_length=10, null=True)),
                ('brca_mutation', models.CharField(blank=True, max_length=10, null=True)),
                ('ki67_level', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('surgery_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tumor_size_before', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tumor_size_3m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tumor_size_6m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tumor_size_12m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tumor_size_24m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('has_metastasis', models.BooleanField(default=False)),
                ('metastasis_sites', models.TextField(blank=True, null=True)),
                ('survival_months', models.IntegerField(blank=True, null=True)),
                ('performance_status', models.CharField(blank=True, max_length=20, null=True)),
                ('tumor_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('lymph_node_status', models.CharField(blank=True, max_length=10, null=True)),
                ('positive_lymph_nodes', models.IntegerField(blank=True, null=True)),
                ('treatment_response', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
