CREATE TABLE patient (
    patient_id SERIAL PRIMARY KEY,
    stage VARCHAR(10) NOT NULL,
    age INTEGER NOT NULL CHECK (age >= 0 AND age <= 120),
    gender VARCHAR(10) NOT NULL CHECK (gender IN ('Female', 'Male')),
    menopausal_status VARCHAR(20) CHECK (menopausal_status IN ('premenopausal', 'perimenopausal', 'postmenopausal', 'Unknown')),
    family_history BOOLEAN,
    molecular_subtype VARCHAR(50) CHECK (molecular_subtype IN ('HR+HER2-', 'HR+HER2+', 'TNBC', 'Unknown')),
    er_status VARCHAR(10) CHECK (er_status IN ('TRUE', 'FALSE', 'Unknown')),
    pr_status VARCHAR(10) CHECK (pr_status IN ('TRUE', 'FALSE', 'Unknown')),
    her2_status VARCHAR(10) CHECK (her2_status IN ('TRUE', 'FALSE', 'Unknown')),
    brca_mutation VARCHAR(10) CHECK (brca_mutation IN ('TRUE', 'FALSE', 'Unknown')),
    ki67_level DECIMAL(5,2) CHECK (ki67_level >= 0 AND ki67_level <= 100),
    treatment TEXT,
    surgery_type VARCHAR(50) CHECK (surgery_type IN ('lumpectomy', 'mastectomy', 'None')),
    tumor_size_before DECIMAL(6,2) CHECK (tumor_size_before >= 0),
    tumor_size_3m DECIMAL(6,2) CHECK (tumor_size_3m >= 0),
    tumor_size_6m DECIMAL(6,2) CHECK (tumor_size_6m >= 0),
    tumor_size_12m DECIMAL(6,2) CHECK (tumor_size_12m >= 0),
    tumor_size_24m DECIMAL(6,2) CHECK (tumor_size_24m >= 0),
    has_metastasis VARCHAR(10) check (has_metastasis IN ('TRUE', 'FALSE', 'Unknown')),
    metastasis_sites VARCHAR(200),
    survival_months INTEGER CHECK (survival_months >= 0),
    performance_status VARCHAR(20) CHECK (performance_status IN ('0', '1', '2', '3', '4', 'Unknown')),
    tumor_grade VARCHAR(5) CHECK (tumor_grade IN ('1', '2', '3', 'X', 'Unknown')),
    lymph_node_status VARCHAR(10) CHECK (lymph_node_status IN ('positive', 'negative', 'Unknown')),
    positive_lymph_nodes INTEGER CHECK (positive_lymph_nodes >= 0),
    treatment_response VARCHAR(50) CHECK (treatment_response IN ('partial', 'stable', 'Unknown')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    result_model_1 VARCHAR(200)
);